#!/bin/bash
#
# all common environment variables needed for the abroute_docker group
#

PG_VERSION=9.4
PG_HOME="/var/lib/postgresql"
PG_CONFDIR="/etc/postgresql/${PG_VERSION}/main"
PG_BINDIR="/usr/lib/postgresql/${PG_VERSION}/bin"
PG_DATADIR="${PG_HOME}/${PG_VERSION}/main"
PSQL_TRUST_LOCALNET=true

export PG_VERSION PG_HOME PG_CONFDIR PG_BINDIR PG_DATADIR PSQL_TRUST_LOCALNET

DB_NAME=autobahn
DB_USER=autouser
DB_PASS=123test
DB_HOST=pg

export DB_NAME DB_USER DB_PASS DB_HOST

WEBSOCKET=ws://router:8080/ws
DSN="dbname=${DB_NAME} host=${DB_HOST} user=${DB_USER}"

set -o vi
